### ISSUE TITLE
Not working on ES 2.0 

### ISSUE THREAD

**Issue by redserpent7** [yakaz/elasticsearch-action-updatebyquery#46]
I tried installing the plugin on a cluster with elasticsearch 2.0. Elasticsearch fails to start and throws this exception:

```Exception in thread "main" java.lang.IllegalStateException: Unable to initialize plugins
Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/action-updatebyquery/plugin-descriptor.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
        at java.nio.file.Files.newInputStream(Files.java:108)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:306)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:112)
        at org.elasticsearch.node.Node.<init>(Node.java:144)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)```


So when should we expect this to be fixed. And is there a workaround for this issue?

**Comment by aamirl** [comment]
Same issue.

**Comment by redserpent7** [comment]
I tried building the code against ES 2.0.1 but there seems to be too many changes. Any ETA on when we could expect an update.

**Comment by ofavre** [comment]
Yes, that's many changes, plus it seems that a few core classes have been removed along with the delete-by-query feature.
I think rebasing update-by-query on the delete-by-query plugin architecture may be easier that porting it directly.

I'm pretty busy so I don't have an ETA yet, sorry.

**Comment by Praveen82** [comment]
Hi Ofavre,

some one look into this issue : https://github.com/yakaz/elasticsearch-action-updatebyquery/issues/47

**Comment by ofavre** [comment]
A new Reindex API has recently been merged inside elasticsearch. It's still inside a feature branch for now, though.
https://github.com/elastic/elasticsearch/pull/15125
It may help speeding up the rewrite a bit by providing more readily reusable source files.
The Reindex API does not use the same endpoints, so the goal is still to adapt that code to create the new implementation but keep the Update By Query API unchanged.

**Comment by fusion52** [comment]
Any updates on this thread?  Seems this would be a core feature.  I was trying to make 2.6.0 work with ES 2.2 but no dice.  That's when I found this thread.  Any recommendations on how to do update-by-query another way?  Thanks.

**Comment by sundarv85** [comment]
+1 We're using 2.1.0 and would like to also do a update-by-query.

**Comment by akshaybijawe** [comment]
Hi, I'm using Elasticsearch V2.1.1. I want to use update by query API. Are there any new updates? or any similar plugins?

**Comment by redserpent7** [comment]
It seems that elastic have implemented their own [update_by_query API](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-update-by-query.html). From the documentation it seems to work the same way as the plugin. Though since its experimental, use at your own risk. Me, I'll wait for a stable version of the new API then upgrade.
